version: "3.9"

services:
    adapter:
        image: newsouthmjos/adapter:1.0.0
        # build: .
        hostname: adapter
        restart: unless-stopped
        environment:
            # Gunicorn server enviroments:
            # - WORKERS_COUNT=1 #NOT WORKING - always 1
            - BIND_ADDRESS=0.0.0.0:8082
            - LOG_LEVEL=info
        ports:
            - 8082:8082

    prometheus_volgar:
        container_name: prometheus_volgar
        image: prom/prometheus
        restart: unless-stopped
        links:
        - adapter:adapter
        volumes: 
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
            - prometheus_volume_dev:/prometheus
        ports: 
            - 9090:9090

    grafana_volgar:
        image: grafana/grafana:latest
        container_name: monitoring_grafana_volgar
        restart: unless-stopped
        links:
        - prometheus_volgar:prometheus_volgar
        volumes:
        - grafana_volume_dev:/var/lib/grafana
        - ./grafana/dashboards:/etc/grafana/provisioning/dashboards/
        - ./grafana/datasources:/etc/grafana/provisioning/datasources/
        environment:
        - GF_SECURITY_ADMIN_PASSWORD=${MY_SECRET_PASS}

        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
        - GF_AUTH_ANONYMOUS_HIDE_VERSION=true
        - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json
        ports: 
            - 80:3000

volumes: 
    prometheus_volume_dev:
    grafana_volume_dev: