global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 1m
  external_labels:
    monitor: codelab-monitor
scrape_configs:
- job_name: volgar_pollution
  honor_timestamps: true
  scrape_interval: 10m
  scrape_timeout: 10s
  metrics_path: /pollutions
  scheme: http
  follow_redirects: true
  static_configs:
  - targets:
    - adapter:8082